### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by xg-wang** [awslabs/amazon-kinesis-client-nodejs#133]
The latest release is v2.1.0 which is 2 years ago https://www.npmjs.com/package/aws-kcl/v/2.1.0.
There are couple of [changes since v2.1.0](https://github.com/awslabs/amazon-kinesis-client-nodejs/compare/v2.1.0..master), is it possible to release a new version?

Thanks!

**Comment by jalateras** [comment]
I would also like to understand when you're planning the next release.

**Comment by jocrau** [comment]
The new release 2.2.0 was tagged Sept. 15. Thanks @zengyu714 for your work on this.

Unfortunately, it has not been released as [NPM package](https://www.npmjs.com/package/aws-kcl), yet. Could anyone please press the button :-)

**Comment by xg-wang** [comment]
https://www.npmjs.com/package/aws-kcl/v/2.2.2 thanks!
