### ISSUE TITLE
Unable to locate java

### ISSUE THREAD

**Issue by KrishanBhasin** [awslabs/amazon-kinesis-client-nodejs#16]
when I run the command
```bash
kcl-bootstrap -e -p ..\samples\basic_sample\consumer\sample.properties
```
from the location of the bootstrap file, I get:
ERROR: Valid --java value is required or alternatively JAVA_HOME environment must be set.

I have set the JAVA_HOME value to point to my java.exe file, and have added the --java [path-to-java] option to my command and still am unable to run the code

**Comment by Phoenix1708** [comment]
Not sure what exactly happened but just want to share some idea: make sure the path to ```java.exe``` doesn't contain things like white space. It's very likely windows people get their java installed in ```Program Files``` or ```Program Files (x86)```

**Comment by KrishanBhasin** [comment]
Can I e get around that by using %20 or do I need to move my java?

%20 isn't working

**Comment by KrishanBhasin** [comment]
I moved Java to a directory with no whitespaces and am still encountering this problem.

**Comment by Phoenix1708** [comment]
I am just trying to give you a hint. Without actually seeing the code, I can't suggest much. Can't you not use the environment variable on Windows like ```--java %JAVA_HOME%\\bin\\java.exe```. Try printing out the path that was actually used. It's interpreted language (well, technically the V8 compiles it to machine code but not the whole program) you can go into libraries and edit it for your debug purposes. Anyway, I am not part of the AWS team, so better off waiting for the offical answer.

**Comment by KrishanBhasin** [comment]
It was my error.
Moving java away from a directory with spaces worked, once I did that I was referencing an incorrect folder. Fixed that and now it works!

**Comment by manoj529** [comment]
Hi @KrishanBhasin  & @Phoenix1708 ,

I'm facing similar issue when i trying to run it in windows machine. However in mac machine its working perfectly without any error.
Please let me know the resolution steps you have taken to run the sample code in windows machine.

Thank you in advance.

**Comment by Eliezergimenes** [comment]
Its work to me: ../../../bin/kcl-bootstrap  /usr/bin/java -e -p sample.properties
