### ISSUE TITLE
Why 2.2.0 is not published to npmjs?

### ISSUE THREAD

**Issue by anatoli-klamer** [awslabs/amazon-kinesis-client-nodejs#188]
npm registry has only 2.1.0 and not 2.2.0
https://www.npmjs.com/package/aws-kcl?activeTab=versions

**Comment by daryl-d** [comment]
+1 @anatoli-klamer  on this, just noticed the same when trying to do security patches

**Comment by UriellVianaDito** [comment]
Also eager to see it published on NPM. The multilang daemon update is very much needed for the new Application level metric.

**Comment by UriellVianaDito** [comment]
@zengyu714 Would you have that type of access to the "[aws-kinesis](https://www.npmjs.com/~aws-kinesis)" npm user? I saw you made the most recent release, but didn't publish it yet.

It would be great if you could help us out 🤞🏼

**Comment by MarcCelani-at** [comment]
@zengyu714 , we workaround this with github url, but we strongly prefer to not use this approach because it is sometimes unreliable on yarn (checksum errors where there should be none). Can you look into publishing this to npm please?

**Comment by zengyu714** [comment]
Hi folks, v2.2.2 has been published to npm: https://www.npmjs.com/package/aws-kcl/v/2.2.2
