### ISSUE TITLE
what is the difference between the amazon kinesis client library and the aws-sdk library for kinesis?

### ISSUE THREAD

**Issue by superpan** [awslabs/amazon-kinesis-client-nodejs#2]

**Comment by rutvikhora** [comment]
Hi,
This link might be helpful to you in understanding the difference between KCL and aws-sdk.
http://docs.aws.amazon.com/kinesis/latest/dev/developing-consumer-apps-with-kcl.html

Let us know if you still have any questions.

**Comment by superpan** [comment]
Thanks for explanation.
