### ISSUE TITLE
Checkpoint Performance Cost?

### ISSUE THREAD

**Issue by aloisbarreras** [awslabs/amazon-kinesis-client-nodejs#35]
I'm wondering what the cost of checkpoint is.

If I needed to checkpoint after each record in a batch, I'm curious if anyone knows if there will be a major performance impact or if it's a cheap operation.

Thanks!

**Comment by pfifer** [comment]
Each call to checkpoint requires a conditional write to DynamoDB.  So the more often you checkpoint the more DynamoDB IOPs are required.
