### ISSUE TITLE
Not able to send data from firehose to ES

### ISSUE THREAD

**Issue by sourcebit-apps** [awslabs/amazon-kinesis-client-nodejs#47]
In my project im streaming logs from cloudwatch kinesis stream. From kinesis stream i have linked to Kinesis firehose which invokes a lambda and transforms the data. The lambda code is one of the blueprints provided when we setup the firehose. I need to send data from firehose lambda to Elastic search as destination.

Now the problem is when i see the firehose logs in cloudwatch i get the below error:

{
    "deliveryStreamARN": "arn:aws:firehose:us-east-2:620209065378:deliverystream/testSBFirehose",
    "destination": "arn:aws:es:us-east-2:620209065378:domain/amcs-test",
    "deliveryStreamVersionId": 2,
    "message": "The ES cluster returned a JsonParseException. Ensure that the data being put is valid.",
    "errorCode": "ES.JsonParseException",
    "processor": "arn:aws:lambda:us-east-2:620209065378:function:streamCloudwatchLogsByKinesis:$LATEST"
}

Please let me know in which form/structure i need to send the data to ES from firehose lambda. Currently im sending data as below format:-

{
    records: [
                          {
                                recordId:''some id",
                                result:"ok",
                                data:"base64 data",
                           }
                   ]
}

**Comment by pfifer** [comment]
Can you please post this to the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=169).  This repository is for the Node.js KCL interface.
