### ISSUE TITLE
upgrade to kcl 2.0

### ISSUE THREAD

**Issue by b-nroths** [awslabs/amazon-kinesis-client-nodejs#55]
Can you provide an implementation with the most recent kcl version (2.0)?

**Comment by mscharp** [comment]
+1 

Also, can you let us know if it's in the works and and a rough ETA?

**Comment by pfifer** [comment]
We are working on it, but I don't have an an ETA right now.  It is a high priority.

**Comment by mscharp** [comment]
Thanks!

**Comment by smergler** [comment]
Is there any update for this now?

**Comment by pfifer** [comment]
Closing this in favor of #56
